"""update user model

Revision ID: 0a645d1f533e
Revises: 56b0704cdcf0
Create Date: 2025-02-22 14:00:38.506626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0a645d1f533e'
down_revision = '56b0704cdcf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weekly_work_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weekly_work_hours')
    # ### end Alembic commands ###
