"""add new model

Revision ID: 24274cb80745
Revises: 42f4d0f2fb17
Create Date: 2025-02-22 08:03:47.354821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '24274cb80745'
down_revision = '42f4d0f2fb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_attendance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('attend_hours', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('attend_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['attend_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'attend_id')
    op.drop_column('user', 'attend_hours')
    op.drop_table('attendance')
    # ### end Alembic commands ###
