"""update user model

Revision ID: 56b0704cdcf0
Revises: a08d4e1d6429
Create Date: 2025-02-22 13:19:50.048528

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56b0704cdcf0'
down_revision = 'a08d4e1d6429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
