"""update user model

Revision ID: a08d4e1d6429
Revises: fa9e729dd7f9
Create Date: 2025-02-22 13:19:26.172964

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a08d4e1d6429'
down_revision = 'fa9e729dd7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('attendance', sa.Column('attend_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'attend_id')
    op.drop_column('attendance', 'full_name')
    # ### end Alembic commands ###
