"""update daily and weekly

Revision ID: d6a3d69d78e5
Revises: 98e4b668deac
Create Date: 2025-02-22 18:23:06.467058

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6a3d69d78e5'
down_revision = '98e4b668deac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailyattendance', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dailyattendance', sa.Column('attend_id', sa.Integer(), nullable=True))
    op.add_column('weeklyattendance', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('weeklyattendance', sa.Column('attend_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weeklyattendance', 'attend_id')
    op.drop_column('weeklyattendance', 'full_name')
    op.drop_column('dailyattendance', 'attend_id')
    op.drop_column('dailyattendance', 'full_name')
    # ### end Alembic commands ###
