"""update user model

Revision ID: e96942e3801f
Revises: 0a645d1f533e
Create Date: 2025-02-22 14:00:52.637324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e96942e3801f'
down_revision = '0a645d1f533e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'weekly_work_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'weekly_work_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
