"""update user model

Revision ID: f26724f1b909
Revises: e96942e3801f
Create Date: 2025-02-22 14:01:39.643516

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f26724f1b909'
down_revision = 'e96942e3801f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'weekly_work_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'weekly_work_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
