"""update user model

Revision ID: fa9e729dd7f9
Revises: 24274cb80745
Create Date: 2025-02-22 08:23:56.413918

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fa9e729dd7f9'
down_revision = '24274cb80745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyattendance',
    sa.Column('total_attendance_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'attend_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('attend_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('dailyattendance')
    # ### end Alembic commands ###
